# Generated by Django 2.2.1 on 2019-05-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournament_date', models.DateTimeField()),
                ('tournament_name', models.CharField(max_length=255)),
                ('tournament_id', models.IntegerField()),
                ('tournament_tier', models.CharField(max_length=32)),
                ('country', models.CharField(max_length=32)),
                ('region', models.CharField(max_length=32)),
            ],
            options={
                'ordering': ['tournament_date'],
            },
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topx', models.IntegerField(null=True)),
                ('p1_id', models.IntegerField(null=True)),
                ('p1_clan', models.CharField(max_length=16)),
                ('p1_stronghold', models.CharField(max_length=32, null=True)),
                ('p1_role', models.CharField(max_length=32)),
                ('p1_points', models.IntegerField()),
                ('p2_id', models.IntegerField(null=True)),
                ('p2_clan', models.CharField(max_length=16)),
                ('p2_stronghold', models.CharField(max_length=32, null=True)),
                ('p2_role', models.CharField(max_length=32)),
                ('p2_points', models.IntegerField()),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='stats.Tournament')),
            ],
            options={
                'order_with_respect_to': 'tournament',
            },
        ),
    ]
